
version: "3.8"

services:

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: ["--config=/etc/otel/otel-collector.yaml"] #, "--log-level=DEBUG"]
    volumes:
      - ./otel-collector.yaml:/etc/otel/otel-collector.yaml
    ports:
      - "4317:4317"
      - "11308:11308" # prometheus metrics export
      - "55680:55680" # default traces port
      - "55681:55681" # default metrics port
    depends_on:
      - jaeger

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - "./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro"
    depends_on:
      - otel-collector
